### PR TITLE
fix BR_EnvSetProperties() erasing <EXT> envelope subchunk

### LINKED ISSUE #1385: reaper.BR_EnvSetProperties killing/ P_EXT for envelopes
When setting a P_EXT for envelopes with reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "Some value", true)

and after use reaper.BR_EnvSetProperties , those P_EXT disappear. but if repeated they stay:
Check the gif: https://imgur.com/pJVn4AZ

Using  this lua : 
--====================================================================
function msg(param)
     reaper.ShowConsoleMsg("\n"..tostring(param));
end

Envelope = reaper.GetSelectedEnvelope(0)
--====================================================================
if Envelope == nil then msg ("Select an envelope") return false end
--====================================================================

reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "Some value", true)

retval, value = reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "", false)
msg ("P_EXT:example holds value:"..value)

local br_env = reaper.BR_EnvAlloc(Envelope, false )   
    reaper.BR_EnvSetProperties( 
      br_env, 
      true,
      true, 
      true, 
      true, 
      10, 
      0, 
      true
   )   
   --====================================================================
reaper.BR_EnvFree( br_env, true )
-- after using reaper.BR_EnvAlloc the value disappears but only on the first run on that envelope
retval, value = reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "", false)
msg ("P_EXT:example holds value:"..value)

### PR DESCRIPTION
**Pull request by nofishonfriday**
fixes #1385 
It seems to work so far. :)

With the test script from #1385 it seemingly only failed for the first run because on the consecutive runs  the envelope properties didn't change anymore (because the properties were already set so from the first run) so  the below was skipped in `BR_Envelope::Commit()` and so the `EXT` subchunk wasn't erased anymore.
https://github.com/reaper-oss/sws/blob/master/Breeder/BR_EnvelopeUtil.cpp#L1468-L1477

### CODE REVIEW

**Comment by cfillion** [comment]
Some `EXT` chunks use base64 encoding via a `BIN` subchunk. Once a `BIN` subchunk is encountered:

- Subsequent EXT data is skipped, thus lost on commit
- The reconstructed envelope chunk on commit becomes corrupted (missing the terminating `>` of the `EXT` chunk)

```lua
-- a new line characters makes REAPER encode the data with base64
reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "\n", true)
reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example2", "this will be lost", true)
```

**Comment by cfillion** [comment]
This would read the entire EXT chunk but it copies the whole envelope chunk and reparses from the start:

```cpp
WDL_FastString chunkCopy(chunk);
SNM_ChunkParserPatcher p(&chunkCopy, false);
p.Parse(SNM_GET_SUBCHUNK_OR_LINE, 2, "EXT", "<EXT", 0, -1, &m_properties.EXT);
```

One way to avoid that could be to count each subchunks while reading line by line.

<details>
<summary>Subchunk counting patch</summary>

```diff
diff --git a/Breeder/BR_EnvelopeUtil.cpp b/Breeder/BR_EnvelopeUtil.cpp
index 63644ea9..9c8c9f30 100644
--- a/Breeder/BR_EnvelopeUtil.cpp
+++ b/Breeder/BR_EnvelopeUtil.cpp
@@ -1889,13 +1889,21 @@ bool BR_Envelope::FillProperties () const
 				}
 				else if (strstr(token, "<EXT"))
 				{
-					// get the <EXT> subchunk
-					m_properties.EXT.Set(token);
-					while (strcmp(token, ">"))
+					AppendLine(m_properties.EXT, token);
+
+					int subchunks = 0;
+					while (subchunks >= 0)
 					{
-						m_properties.EXT.Append("\n");
 						token = strtok(NULL, "\n");
-						m_properties.EXT.Append(token);
+						if (!token)
+							break;
+
+						if (strstr(token, "<") == token)
+							++subchunks;
+						if(!strcmp(token, ">"))
+							--subchunks
+
+						AppendLine(m_properties.EXT, token);
 					}
 				}
 
@@ -1930,7 +1938,7 @@ WDL_FastString BR_Envelope::GetProperties ()
 		}
 		if (m_properties.faderMode != 0) properties.AppendFormatted(256, "VOLTYPE %d\n", 1);
 		if (m_properties.EXT.GetLength())
-			properties.AppendFormatted(m_properties.EXT.GetLength()+1, "%s\n", m_properties.EXT.Get());
+			properties.Append(m_properties.EXT.Get());
 		return properties;
 	}
 	else
```
</details>

Another way is to rewrite `FillProperties` to use `SNM_ChunkParserPatcher`.
<details>
<summary>SNM_ChunkParserPatcher rewrite patch</summary>

```diff
diff --git a/Breeder/BR_EnvelopeUtil.cpp b/Breeder/BR_EnvelopeUtil.cpp
index 63644ea9..a0d1703f 100644
--- a/Breeder/BR_EnvelopeUtil.cpp
+++ b/Breeder/BR_EnvelopeUtil.cpp
@@ -1754,161 +1754,163 @@ void BR_Envelope::FillFxInfo ()
 	}
 }
 
-bool BR_Envelope::FillProperties () const
-{
-	if (!m_properties.filled)
+class EnvelopePropertiesParser : public SNM_ChunkParserPatcher {
+public:
+	EnvelopePropertiesParser(WDL_FastString &chunk, BR_Envelope::EnvProperties *props)
+		: SNM_ChunkParserPatcher(&chunk, false, true), m_properties{props}
+	{}
+
+protected:
+	bool NotifyChunkLine(int, LineParser *lp, const char *line, int, int,
+		WDL_PtrList<WDL_FastString> *parents, WDL_FastString *, int) override
 	{
-		char* chunk    = NULL;
-		bool freeChunk = false;
-		if (m_chunkProperties.GetLength())
+		if (parents->GetSize() == 1)
+			parseProperty(lp, line);
+		else if (parents->GetSize() >= 2 && !strcmp("EXT", parents->Get(1)->Get()))
+			AppendLine(m_properties->EXT, line);
+
+		return false;
+	}
+
+	bool NotifyEndElement(int, LineParser *, const char *line, int,
+		WDL_PtrList<WDL_FastString> *parents, WDL_FastString *, int) override
+	{
+		if (parents->GetSize() == 2 && !strcmp("EXT", parents->Get(1)->Get()))
+			AppendLine(m_properties->EXT, line);
+		return false;
+	}
+
+private:
+	void parseProperty(LineParser *lp, const char *line)
+	{
+		const char *token = lp->gettoken_str(0);
+
+		if (!strcmp(token, "PT"))
+			m_breakParsePatch = true;
+		else if (!strcmp(token, "ACT"))
 		{
-			size_t size = m_chunkProperties.GetLength()+1;
-			if ((chunk = new (nothrow) char[size]))
-				memcpy(chunk, m_chunkProperties.Get(), size);
+			m_properties->active    = lp->gettoken_int(1);
+			m_properties->AIoptions = lp->gettoken_int(2);
 		}
-		else
+		else if (!strcmp(token, "VIS"))
 		{
-			chunk = GetSetObjectState(m_envelope, "");
-			freeChunk = true;
+			m_properties->visible    = lp->gettoken_int(1);
+			m_properties->lane       = lp->gettoken_int(2);
+			m_properties->visUnknown = lp->gettoken_int(3);
 		}
-
-		if (chunk)
+		else if (!strcmp(token, "LANEHEIGHT"))
 		{
-			LineParser lp(false);
-			char* token = strtok(chunk, "\n");
-			while (token != NULL)
-			{
-				if (!strncmp(token, "PT ", sizeof("PT ")-1))
-				{
-					break;
-				}
-				else if (!strncmp(token, "ACT ", sizeof("ACT ")-1))
-				{
-					lp.parse(token);
-					m_properties.active    = lp.gettoken_int(1);
-					m_properties.AIoptions = lp.gettoken_int(2);
-				}
-				else if (!strncmp(token, "VIS ", sizeof("VIS ")-1))
-				{
-					lp.parse(token);
-					m_properties.visible    = lp.gettoken_int(1);
-					m_properties.lane       = lp.gettoken_int(2);
-					m_properties.visUnknown = lp.gettoken_int(3);
-				}
-				else if (!strncmp(token, "LANEHEIGHT ", sizeof("LANEHEIGHT ")-1))
-				{
-					lp.parse(token);
-					m_properties.height        = lp.gettoken_int(1);
-					m_properties.heightUnknown = lp.gettoken_int(2);
-				}
-				else if (!strncmp(token, "ARM ", sizeof("ARM ")-1))
-				{
-					lp.parse(token);
-					m_properties.armed = lp.gettoken_int(1);
-				}
-				else if (!strncmp(token, "DEFSHAPE ", sizeof("DEFSHAPE ")-1))
-				{
-					lp.parse(token);
-					m_properties.shape         = lp.gettoken_int(1);
-					m_properties.shapeUnknown1 = lp.gettoken_int(2);
-					m_properties.shapeUnknown2 = lp.gettoken_int(3);
-				}
-				else if (!strncmp(token, "VOLTYPE ", sizeof("VOLTYPE ")-1))
-				{
-					lp.parse(token);
-					m_properties.faderMode = lp.gettoken_int(1);
-				}
-				else if (strstr(token, "PARMENV"))
-				{
-					lp.parse(token);
-					m_properties.minValue    = lp.gettoken_float(2);
-					m_properties.maxValue    = lp.gettoken_float(3);
-					m_properties.centerValue = lp.gettoken_float(4);
-					m_properties.type = PARAMETER;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "VOLENV"))
-				{
-					m_properties.minValue = 0;
-					m_properties.maxValue = 16;
-					m_properties.centerValue = 1;
-					m_properties.type = (strstr(token, "AUXVOLENV") || strstr(token, "VOLENV2") || strstr(token, "HWVOLENV")) ? VOLUME : VOLUME_PREFX;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "PANENV"))
-				{
-					m_properties.minValue = -1;
-					m_properties.maxValue = 1;
-					m_properties.centerValue = 0;
-					m_properties.type = (strstr(token, "AUXPANENV") || strstr(token, "PANENV2") || strstr(token, "HWPANENV")) ? PAN : PAN_PREFX;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "WIDTHENV"))
-				{
-					m_properties.minValue = -1;
-					m_properties.maxValue = 1;
-					m_properties.centerValue = 0;
-					m_properties.type = (strstr(token, "WIDTHENV2")) ? WIDTH : WIDTH_PREFX;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "MUTEENV"))
-				{
-					m_properties.minValue = 0;
-					m_properties.maxValue = 1;
-					m_properties.centerValue = 0.5;
-					m_properties.type = MUTE;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "SPEEDENV"))
-				{
-					m_properties.minValue = 0.1;
-					m_properties.maxValue = 4;
-					m_properties.centerValue = 1;
-					m_properties.type = PLAYRATE;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "PITCHENV"))
-				{
-					m_properties.minValue = -255;
-					m_properties.maxValue = 255;
-					m_properties.centerValue = 0;
-					m_properties.type = PITCH;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "TEMPOENV"))
-				{
-					m_properties.minValue = MIN_BPM;
-					m_properties.maxValue = MAX_BPM;
-					m_properties.centerValue = (m_properties.maxValue + m_properties.minValue) / 2;
-					m_properties.type = TEMPO;
-					m_properties.paramType.Set(token);
-				}
-				else if (strstr(token, "POOLEDENVINST"))
-				{
-					m_properties.automationItems.push_back(WDL_FastString(token));
-				}
-				else if (strstr(token, "<EXT"))
-				{
-					// get the <EXT> subchunk
-					m_properties.EXT.Set(token);
-					while (strcmp(token, ">"))
-					{
-						m_properties.EXT.Append("\n");
-						token = strtok(NULL, "\n");
-						m_properties.EXT.Append(token);
-					}
-				}
-
-				token = strtok(NULL, "\n");
-			}
-
-			if (freeChunk) FreeHeapPtr(chunk);
-			else           delete [] chunk;
-			m_properties.filled = true;
+			m_properties->height        = lp->gettoken_int(1);
+			m_properties->heightUnknown = lp->gettoken_int(2);
+		}
+		else if (!strcmp(token, "ARM"))
+		{
+			m_properties->armed = lp->gettoken_int(1);
+		}
+		else if (!strcmp(token, "DEFSHAPE"))
+		{
+			m_properties->shape         = lp->gettoken_int(1);
+			m_properties->shapeUnknown1 = lp->gettoken_int(2);
+			m_properties->shapeUnknown2 = lp->gettoken_int(3);
+		}
+		else if (!strcmp(token, "VOLTYPE"))
+		{
+			m_properties->faderMode = lp->gettoken_int(1);
+		}
+		else if (strstr(token, "PARMENV"))
+		{
+			m_properties->minValue    = lp->gettoken_float(2);
+			m_properties->maxValue    = lp->gettoken_float(3);
+			m_properties->centerValue = lp->gettoken_float(4);
+			m_properties->type = PARAMETER;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "VOLENV"))
+		{
+			m_properties->minValue = 0;
+			m_properties->maxValue = 16;
+			m_properties->centerValue = 1;
+			m_properties->type = (strstr(token, "AUXVOLENV") || strstr(token, "VOLENV2") || strstr(token, "HWVOLENV")) ? VOLUME : VOLUME_PREFX;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "PANENV"))
+		{
+			m_properties->minValue = -1;
+			m_properties->maxValue = 1;
+			m_properties->centerValue = 0;
+			m_properties->type = (strstr(token, "AUXPANENV") || strstr(token, "PANENV2") || strstr(token, "HWPANENV")) ? PAN : PAN_PREFX;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "WIDTHENV"))
+		{
+			m_properties->minValue = -1;
+			m_properties->maxValue = 1;
+			m_properties->centerValue = 0;
+			m_properties->type = (strstr(token, "WIDTHENV2")) ? WIDTH : WIDTH_PREFX;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "MUTEENV"))
+		{
+			m_properties->minValue = 0;
+			m_properties->maxValue = 1;
+			m_properties->centerValue = 0.5;
+			m_properties->type = MUTE;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "SPEEDENV"))
+		{
+			m_properties->minValue = 0.1;
+			m_properties->maxValue = 4;
+			m_properties->centerValue = 1;
+			m_properties->type = PLAYRATE;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "PITCHENV"))
+		{
+			m_properties->minValue = -255;
+			m_properties->maxValue = 255;
+			m_properties->centerValue = 0;
+			m_properties->type = PITCH;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "TEMPOENV"))
+		{
+			m_properties->minValue = MIN_BPM;
+			m_properties->maxValue = MAX_BPM;
+			m_properties->centerValue = (m_properties->maxValue + m_properties->minValue) / 2;
+			m_properties->type = TEMPO;
+			m_properties->paramType.Set(token);
+		}
+		else if (strstr(token, "POOLEDENVINST"))
+		{
+			m_properties->automationItems.push_back(WDL_FastString(line));
 		}
 	}
 
-	return m_properties.filled;
+	BR_Envelope::EnvProperties *m_properties;
+};
+
+bool BR_Envelope::FillProperties () const
+{
+	if (m_properties.filled)
+		return true;
+
+	WDL_FastString chunk;
+
+	if (m_chunkProperties.GetLength())
+		chunk.Set(m_chunkProperties.Get());
+	else
+		chunk.Set(GetSetObjectState(m_envelope, ""));
+
+	if (!chunk.GetLength())
+		return false;
+
+	EnvelopePropertiesParser p(chunk, &m_properties);
+	p.Parse(-1);
+
+	m_properties.filled = true;
+
+	return true;
 }
 
 WDL_FastString BR_Envelope::GetProperties ()
@@ -1930,7 +1938,7 @@ WDL_FastString BR_Envelope::GetProperties ()
 		}
 		if (m_properties.faderMode != 0) properties.AppendFormatted(256, "VOLTYPE %d\n", 1);
 		if (m_properties.EXT.GetLength())
-			properties.AppendFormatted(m_properties.EXT.GetLength()+1, "%s\n", m_properties.EXT.Get());
+			properties.Append(m_properties.EXT.Get());
 		return properties;
 	}
 	else
diff --git a/Breeder/BR_EnvelopeUtil.h b/Breeder/BR_EnvelopeUtil.h
index 631815ed..30d4ec5f 100644
--- a/Breeder/BR_EnvelopeUtil.h
+++ b/Breeder/BR_EnvelopeUtil.h
@@ -165,11 +165,6 @@ public:
 	/* Committing - does absolutely nothing if there are no edits or locking is turned on (unless forced) */
 	bool Commit (bool force = false);
 
-private:
-	struct IdPair
-	{
-		int first, second;
-	};
 	struct EnvProperties
 	{
 		int active, AIoptions; // automation items options, second ACT token in track env. chunk
@@ -205,6 +200,11 @@ private:
 		//	bool extra2; 
 		//};
 	};
+private:
+	struct IdPair
+	{
+		int first, second;
+	};
 	struct EnvPoint
 	{
 		double position;
```
</details>

**Comment by nofishonfriday** [comment]
Thanks. Went with option 2. (PR updated)
How did you know about the BIN subchunk (never noticed/encountered it personally)?
I've also just updated [sws-2-12-1](https://github.com/reaper-oss/sws/pull/1370).

File: Breeder/BR_EnvelopeUtil.cpp [hunk 1]
```diff
@@ -1887,6 +1887,21 @@ bool BR_Envelope::FillProperties () const
...
+
+					do
+					{
+						if (*token == '<')
+							++subchunks;
+						else if (!strcmp(token, ">"))
+							--subchunks;
+					
+							AppendLine(m_properties.EXT, token);
+							token = strtok(NULL, "\n");
```
Comment (cfillion) [inline Breeder/BR_EnvelopeUtil.cpp:1902]: > How did you know about the BIN subchunk (never noticed/encountered it personally)?

The code was looking for a line with ">" to stop the loop so I wondered what would happen if the data contained that. REAPER inserted a <BIN subchunk when I tried "foo\n>".

---

Indentation fix:
```suggestion
						AppendLine(m_properties.EXT, token);
						token = strtok(NULL, "\n");
```

Comment (nofishonfriday) [reply Breeder/BR_EnvelopeUtil.cpp:1902]: Can I make a new dedicated commit for this on the `sws-2-12-1` branch?
Otherwise I wouldn't know how to fix it there because I've already merged other PR's afterwards (maybe I've been a bit too fast with merging..)

Comment (cfillion) [reply Breeder/BR_EnvelopeUtil.cpp:1902]: I also pushed a new version of PR #1352 after it was merged. If you don't mind, I can try amending the 2.12.1 branch's history to replace the commits with the newer ones from those two PRs.

Comment (nofishonfriday) [reply Breeder/BR_EnvelopeUtil.cpp:1902]: That would be nice, I never figured out how to alter/amend 'in between' (i.e. not the latest) commit properly.
Thanks.
